### PR TITLE
Improvements to the spelling and grammar of the README.

### PR DESCRIPTION
**Pull request by philipaconrad**
I've made some minor improvements and corrections on the README. Things I've touched up:

-A number of spelling and grammatical errors.
-Reworded a few awkward sentences to convey the same meaning in a more concise and clear way.
-Reformatted some areas of the README, such as applying the "code-highlight" style to the 'if' and 'for' tags.
-Other minor enhancements.

Enjoy!

### CODE REVIEW

**Comment by philipaconrad** [comment]
Are you completely averse to anybody editing the README and/or docs? If that is the case, I'll delete my fork and we'll all be happier creatures.

However, if there is anything I can do to make my version of the README more suitable to you, just let me know. I'd be happy to fix it.

**Comment by speedmax** [comment]
I clicked on the wrong button :)

**Comment by speedmax** [comment]
Thank you very much for all those edits.

**Comment by philipaconrad** [comment]
You're welcome.

**Pull request merged**
